{
   "swagger":"2.0",
   "info":{
      "title":"server",
      "description":"SAFRSAPI",
      "termsOfService":"",
      "version":"0.0"
   },
   "host":"127.0.0.1:5000",
   "paths":{
      "/messages/":{
         "get":{
            "tags":[
               "messages"
            ],
            "summary":"Retrieve a collection of Message objects",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message relationships to include (csv)"
               },
               {
                  "default":"message,userFrom,userTo",
                  "type":"string",
                  "name":"fields[Message]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message fields to include (csv)"
               },
               {
                  "default":0,
                  "type":"integer",
                  "name":"page[offset]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Page offset"
               },
               {
                  "default":10,
                  "type":"integer",
                  "name":"page[limit]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Max number of items"
               },
               {
                  "default":"message,userFrom,userTo,id",
                  "type":"string",
                  "name":"sort",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Sort order"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[message]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"message attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[userFrom]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"userFrom attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[userTo]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"userTo attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[id]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"id attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Custom Message filter"
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Message_coll1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve Message from messages",
            "operationId":"RetrieveacollectionofMessageobjects_0"
         },
         "post":{
            "tags":[
               "messages"
            ],
            "summary":"Create Message",
            "parameters":[
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"POST body",
                  "in":"body",
                  "description":"Message attributes",
                  "schema":{
                     "$ref":"#/definitions/Message_inst1"
                  },
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "202":{
                  "description":"Accepted"
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "201":{
                  "schema":{
                     "$ref":"#/definitions/Message_inst1"
                  },
                  "description":"Created"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"CreateMessage_0"
         }
      },
      "/messages/{MessageId}/":{
         "get":{
            "tags":[
               "messages"
            ],
            "summary":"Retrieve Message instance",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message relationships to include (csv)"
               },
               {
                  "default":"message,userFrom,userTo",
                  "type":"string",
                  "name":"fields[Message]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message fields to include (csv)"
               },
               {
                  "name":"MessageId",
                  "in":"path",
                  "type":"string",
                  "default":"ab584674-16e3-4114-ac04-fafaf775ac1b",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Message_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve Message from messages",
            "operationId":"RetrieveMessageinstance_0"
         },
         "patch":{
            "tags":[
               "messages"
            ],
            "parameters":[
               {
                  "name":"MessageId",
                  "in":"path",
                  "type":"string",
                  "default":"ab584674-16e3-4114-ac04-fafaf775ac1b",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"PATCH body",
                  "in":"body",
                  "description":"Message attributes",
                  "schema":{
                     "$ref":"#/definitions/Message_inst"
                  },
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"No Content"
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Message_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Update Message",
            "description":"Update Message attributes",
            "operationId":"UpdateMessage_0"
         },
         "delete":{
            "tags":[
               "messages"
            ],
            "parameters":[
               {
                  "name":"MessageId",
                  "in":"path",
                  "type":"string",
                  "default":"ab584674-16e3-4114-ac04-fafaf775ac1b",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"Request fulfilled, nothing follows"
               },
               "200":{
                  "description":"Success",
                  "schema":{
                     "$ref":"#/definitions/Message_inst1"
                  }
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Delete Message from messages",
            "operationId":"DeleteMessagefrommessages_0"
         }
      },
      "/messages/{MessageId}/getMessageFromUser":{
         "get":{
            "tags":[
               "messages"
            ],
            "description":"Get message from user",
            "summary":"Invoke Message.getMessageFromUser",
            "responses":{
               "200":{
                  "description":"Request fulfilled, document follows",
                  "schema":{
                     "$ref":"#/definitions/User_coll1"
                  }
               }
            },
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message relationships to include (csv)"
               },
               {
                  "default":"message,userFrom,userTo",
                  "type":"string",
                  "name":"fields[Message]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Message fields to include (csv)"
               },
               {
                  "name":"varargs",
                  "in":"query",
                  "description":"getMessageFromUser arguments",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"MessageId",
                  "in":"path",
                  "type":"string",
                  "default":"ab584674-16e3-4114-ac04-fafaf775ac1b",
                  "required":true
               }
            ],
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"InvokeMessagegetMessageFromUser_0"
         }
      },
      "/online/":{
         "get":{
            "tags":[
               "online"
            ],
            "summary":"Retrieve a collection of Online objects",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Online relationships to include (csv)"
               },
               {
                  "default":"login,czas",
                  "type":"string",
                  "name":"fields[Online]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Online fields to include (csv)"
               },
               {
                  "default":0,
                  "type":"integer",
                  "name":"page[offset]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Page offset"
               },
               {
                  "default":10,
                  "type":"integer",
                  "name":"page[limit]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Max number of items"
               },
               {
                  "default":"login,czas,id",
                  "type":"string",
                  "name":"sort",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Sort order"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[login]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"login attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[czas]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"czas attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[id]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"id attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Custom Online filter"
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Online_coll1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve Online from online",
            "operationId":"RetrieveacollectionofOnlineobjects_0"
         },
         "post":{
            "tags":[
               "online"
            ],
            "summary":"Create Online",
            "parameters":[
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"POST body",
                  "in":"body",
                  "description":"Online attributes",
                  "schema":{
                     "$ref":"#/definitions/Online_inst1"
                  },
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "202":{
                  "description":"Accepted"
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "201":{
                  "schema":{
                     "$ref":"#/definitions/Online_inst1"
                  },
                  "description":"Created"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"CreateOnline_0"
         }
      },
      "/online/{OnlineId}/":{
         "get":{
            "tags":[
               "online"
            ],
            "summary":"Retrieve Online instance",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Online relationships to include (csv)"
               },
               {
                  "default":"login,czas",
                  "type":"string",
                  "name":"fields[Online]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Online fields to include (csv)"
               },
               {
                  "name":"OnlineId",
                  "in":"path",
                  "type":"string",
                  "default":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Online_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve Online from online",
            "operationId":"RetrieveOnlineinstance_0"
         },
         "patch":{
            "tags":[
               "online"
            ],
            "parameters":[
               {
                  "name":"OnlineId",
                  "in":"path",
                  "type":"string",
                  "default":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"PATCH body",
                  "in":"body",
                  "description":"Online attributes",
                  "schema":{
                     "$ref":"#/definitions/Online_inst"
                  },
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"No Content"
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/Online_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Update Online",
            "description":"Update Online attributes",
            "operationId":"UpdateOnline_0"
         },
         "delete":{
            "tags":[
               "online"
            ],
            "parameters":[
               {
                  "name":"OnlineId",
                  "in":"path",
                  "type":"string",
                  "default":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"Request fulfilled, nothing follows"
               },
               "200":{
                  "description":"Success",
                  "schema":{
                     "$ref":"#/definitions/Online_inst1"
                  }
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Delete Online from online",
            "operationId":"DeleteOnlinefromonline_0"
         }
      },
      "/users/":{
         "get":{
            "tags":[
               "users"
            ],
            "summary":"Retrieve a collection of User objects",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User relationships to include (csv)"
               },
               {
                  "default":"login,password",
                  "type":"string",
                  "name":"fields[User]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User fields to include (csv)"
               },
               {
                  "default":0,
                  "type":"integer",
                  "name":"page[offset]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Page offset"
               },
               {
                  "default":10,
                  "type":"integer",
                  "name":"page[limit]",
                  "in":"query",
                  "format":"int64",
                  "required":false,
                  "description":"Max number of items"
               },
               {
                  "default":"login,password,id",
                  "type":"string",
                  "name":"sort",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Sort order"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[login]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"login attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[password]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"password attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter[id]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"id attribute filter (csv)"
               },
               {
                  "default":"",
                  "type":"string",
                  "name":"filter",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"Custom User filter"
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/User_coll1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve User from users",
            "operationId":"RetrieveacollectionofUserobjects_0"
         },
         "post":{
            "tags":[
               "users"
            ],
            "summary":"Create User",
            "parameters":[
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"POST body",
                  "in":"body",
                  "description":"User attributes",
                  "schema":{
                     "$ref":"#/definitions/User_inst1"
                  },
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "202":{
                  "description":"Accepted"
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "201":{
                  "schema":{
                     "$ref":"#/definitions/User_inst1"
                  },
                  "description":"Created"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"CreateUser_0"
         }
      },
      "/users/{UserId}/":{
         "get":{
            "tags":[
               "users"
            ],
            "summary":"Retrieve User instance",
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User relationships to include (csv)"
               },
               {
                  "default":"login,password",
                  "type":"string",
                  "name":"fields[User]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User fields to include (csv)"
               },
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/User_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "description":"Retrieve User from users",
            "operationId":"RetrieveUserinstance_0"
         },
         "patch":{
            "tags":[
               "users"
            ],
            "parameters":[
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               },
               {
                  "name":"PATCH body",
                  "in":"body",
                  "description":"User attributes",
                  "schema":{
                     "$ref":"#/definitions/User_inst"
                  },
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"No Content"
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "409":{
                  "description":"Conflict",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_409"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               },
               "200":{
                  "schema":{
                     "$ref":"#/definitions/User_inst1"
                  },
                  "description":"Request fulfilled, document follows"
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Update User",
            "description":"Update User attributes",
            "operationId":"UpdateUser_0"
         },
         "delete":{
            "tags":[
               "users"
            ],
            "parameters":[
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               },
               {
                  "name":"Content-Type",
                  "in":"header",
                  "type":"string",
                  "default":"application/vnd.api+json",
                  "enum":[
                     "application/vnd.api+json",
                     "application/json"
                  ],
                  "required":true
               }
            ],
            "responses":{
               "202":{
                  "description":"Accepted"
               },
               "204":{
                  "description":"Request fulfilled, nothing follows"
               },
               "200":{
                  "description":"Success",
                  "schema":{
                     "$ref":"#/definitions/User_inst1"
                  }
               },
               "403":{
                  "description":"Forbidden",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_403"
                  }
               },
               "404":{
                  "description":"Not Found",
                  "schema":{
                     "$ref":"#/definitions/jsonapi_error_404"
                  }
               }
            },
            "produces":[
               "application/vnd.api+json"
            ],
            "summary":"Delete User from users",
            "operationId":"DeleteUserfromusers_0"
         }
      },
      "/users/{UserId}/addMessage":{
         "get":{
            "tags":[
               "users"
            ],
            "description":"Send a message to user",
            "summary":"Invoke User.addMessage",
            "responses":{
               "200":{
                  "description":"Request fulfilled, document follows"
               }
            },
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User relationships to include (csv)"
               },
               {
                  "default":"login,password",
                  "type":"string",
                  "name":"fields[User]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User fields to include (csv)"
               },
               {
                  "name":"varargs",
                  "in":"query",
                  "description":"addMessage arguments",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               }
            ],
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"InvokeUseraddMessage_0"
         },
         "post":{
            "tags":[
               "users"
            ],
            "description":"Send a message to user",
            "summary":"Invoke User.addMessage",
            "responses":{
               "200":{
                  "description":"Request fulfilled, document follows"
               }
            },
            "parameters":[
               {
                  "name":"post_User_addMessage",
                  "in":"body",
                  "description":"Send a message to user",
                  "schema":{
                     "$ref":"#/definitions/post_User_addMessage"
                  },
                  "required":true
               },
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               }
            ],
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"InvokeUseraddMessage_1"
         }
      },
      "/users/{UserId}/addUser":{
         "get":{
            "tags":[
               "users"
            ],
            "description":"Register a new user",
            "summary":"Invoke User.addUser",
            "responses":{
               "200":{
                  "description":"Request fulfilled, document follows"
               }
            },
            "parameters":[
               {
                  "default":"",
                  "type":"string",
                  "name":"include",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User relationships to include (csv)"
               },
               {
                  "default":"login,password",
                  "type":"string",
                  "name":"fields[User]",
                  "in":"query",
                  "format":"string",
                  "required":false,
                  "description":"User fields to include (csv)"
               },
               {
                  "name":"varargs",
                  "in":"query",
                  "description":"addUser arguments",
                  "required":false,
                  "type":"string"
               },
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               }
            ],
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"InvokeUseraddUser_0"
         },
         "post":{
            "tags":[
               "users"
            ],
            "description":"Register a new user",
            "summary":"Invoke User.addUser",
            "responses":{
               "200":{
                  "description":"Request fulfilled, document follows"
               }
            },
            "parameters":[
               {
                  "name":"post_User_addUser",
                  "in":"body",
                  "description":"Register a new user",
                  "schema":{
                     "$ref":"#/definitions/post_User_addUser"
                  },
                  "required":true
               },
               {
                  "name":"UserId",
                  "in":"path",
                  "type":"string",
                  "default":"user0",
                  "required":true
               }
            ],
            "produces":[
               "application/vnd.api+json"
            ],
            "operationId":"InvokeUseraddUser_1"
         }
      }
   },
   "definitions":{
      "post_User_addMessage":{
         "properties":{
            "meta":{
               "$ref":"#/definitions/User_addMessage"
            }
         },
         "description":""
      },
      "User_addMessage":{
         "properties":{
            "method":{
               "example":"addMessage",
               "type":"string"
            },
            "args":{
               "example":{
                  "message":{
                     "type":"string",
                     "example":"Hello"
                  },
                  "userFrom":{
                     "type":"string",
                     "example":"user1"
                  },
                  "userTo":{
                     "type":"string",
                     "example":"user2"
                  }
               },
               "type":"string"
            }
         },
         "description":""
      },
      "post_User_addUser":{
         "properties":{
            "meta":{
               "$ref":"#/definitions/User_addUser"
            }
         },
         "description":""
      },
      "User_addUser":{
         "properties":{
            "method":{
               "example":"addUser",
               "type":"string"
            },
            "args":{
               "example":{
                  "login":{
                     "type":"string",
                     "example":"user1"
                  },
                  "password":{
                     "type":"string",
                     "example":"142aa"
                  }
               },
               "type":"string"
            }
         },
         "description":""
      },
      "jsonapi_error_403":{
         "properties":{
            "errors":{
               "example":[
                  {
                     "title":"Request forbidden -- authorization will not help",
                     "detail":"",
                     "code":"403"
                  }
               ],
               "type":"string"
            }
         },
         "description":""
      },
      "jsonapi_error_404":{
         "properties":{
            "errors":{
               "example":[
                  {
                     "title":"Nothing matches the given URI",
                     "detail":"",
                     "code":"404"
                  }
               ],
               "type":"string"
            }
         },
         "description":""
      },
      "User_coll1":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "login":"",
                        "password":"1111"
                     },
                     "type":"User",
                     "id":"user0",
                     "relationships":{

                     }
                  }
               ],
               "type":"string"
            }
         },
         "description":"User get;"
      },
      "User_inst1":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "login":"",
                     "password":"1111"
                  },
                  "type":"User"
               },
               "type":"string"
            }
         },
         "description":"User post;"
      },
      "jsonapi_error_409":{
         "properties":{
            "errors":{
               "example":[
                  {
                     "title":"Request conflict",
                     "detail":"",
                     "code":"409"
                  }
               ],
               "type":"string"
            }
         },
         "description":""
      },
      "User_inst":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "login":"",
                     "password":"1111"
                  },
                  "type":"User",
                  "id":"user0"
               },
               "type":"string"
            }
         },
         "description":"User patch;User post;User delete;User patch;User post;User delete;"
      },
      "Invoke _User_addMessage":{
         "properties":{

         }
      },
      "Invoke _User_addUser":{
         "properties":{

         }
      },
      "User_coll":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "login":"",
                        "password":"1111"
                     },
                     "type":"User",
                     "id":"user0"
                  }
               ],
               "type":"string"
            }
         }
      },
      "post_Message_getMessageFromUser":{
         "properties":{
            "meta":{
               "$ref":"#/definitions/Message_getMessageFromUser"
            }
         },
         "description":""
      },
      "Message_getMessageFromUser":{
         "properties":{
            "method":{
               "example":"getMessageFromUser",
               "type":"string"
            },
            "args":{
               "example":{
                  "userFrom":{
                     "type":"string",
                     "example":"user1"
                  },
                  "userTo":{
                     "type":"string",
                     "example":"user2"
                  }
               },
               "type":"string"
            }
         },
         "description":""
      },
      "Message_coll1":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "message":"hi",
                        "userFrom":"user1",
                        "userTo":"user2"
                     },
                     "type":"Message",
                     "id":"ab584674-16e3-4114-ac04-fafaf775ac1b",
                     "relationships":{

                     }
                  }
               ],
               "type":"string"
            }
         },
         "description":"Message get;"
      },
      "Message_inst1":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "message":"hi",
                     "userFrom":"user1",
                     "userTo":"user2"
                  },
                  "type":"Message"
               },
               "type":"string"
            }
         },
         "description":"Message post;"
      },
      "Message_inst":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "message":"hi",
                     "userFrom":"user1",
                     "userTo":"user2"
                  },
                  "type":"Message",
                  "id":"ab584674-16e3-4114-ac04-fafaf775ac1b"
               },
               "type":"string"
            }
         },
         "description":"Message patch;Message post;Message delete;Message patch;Message post;Message delete;"
      },
      "Invoke _Message_getMessageFromUser":{
         "properties":{

         }
      },
      "Message_coll":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "message":"hi",
                        "userFrom":"user1",
                        "userTo":"user2"
                     },
                     "type":"Message",
                     "id":"ab584674-16e3-4114-ac04-fafaf775ac1b"
                  }
               ],
               "type":"string"
            }
         }
      },
      "Online_coll1":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "login":"user1",
                        "czas":"12/20/2020 16:30"
                     },
                     "type":"Online",
                     "id":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d",
                     "relationships":{

                     }
                  }
               ],
               "type":"string"
            }
         },
         "description":"Online get;"
      },
      "Online_inst1":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "login":"user1",
                     "czas":"12/20/2020 16:30"
                  },
                  "type":"Online"
               },
               "type":"string"
            }
         },
         "description":"Online post;"
      },
      "Online_inst":{
         "properties":{
            "data":{
               "example":{
                  "attributes":{
                     "login":"user1",
                     "czas":"12/20/2020 16:30"
                  },
                  "type":"Online",
                  "id":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d"
               },
               "type":"string"
            }
         },
         "description":"Online patch;Online post;Online delete;Online patch;Online post;Online delete;"
      },
      "Online_coll":{
         "properties":{
            "data":{
               "example":[
                  {
                     "attributes":{
                        "login":"user1",
                        "czas":"12/20/2020 16:30"
                     },
                     "type":"Online",
                     "id":"06ea2657-cccd-4d80-81e3-ddc1eb69e35d"
                  }
               ],
               "type":"string"
            }
         }
      }
   },
   "tags":[
      {
         "description":"User description",
         "name":"users"
      },
      {
         "description":"Message description",
         "name":"messages"
      },
      {
         "description":"Online description",
         "name":"online"
      }
   ]
}